# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."booklore" = {
    image = "booklore/booklore:latest";
    environment = {
      "BOOKLORE_PORT" = "6060";
      "DATABASE_PASSWORD" = "/run/secrets/Booklore/Secrets/DB_PASSWORD";
      "DATABASE_URL" = "/run/secrets/Booklore/Secrets/DATABASE_URL";
      "DATABASE_USERNAME" = "/run/secrets/Booklore/Secrets/DB_USER";
      "GROUP_ID" = "/run/secrets/Booklore/Secrets/APP_GROUP_ID";
      "TZ" = "/run/secrets/Booklore/Secrets/TZ";
      "USER_ID" = "/run/secrets/Booklore/Secrets/APP_USER_ID";
    };
    volumes = [
      "/home/howard/booklore/booklore/bookdrop:/bookdrop:rw"
      "/home/howard/booklore/booklore/books:/books:rw"
      "/home/howard/booklore/booklore/data:/app/data:rw"
    ];
    ports = [ "6060:6060/tcp" ];
    labels = {
      "compose2nix.settings.sops.secrets" = "Booklore/Secrets/APP_USER_ID,Booklore/Secrets/APP_GROUP_ID,Booklore/Secrets/TZ,Booklore/Secrets/BOOKLORE_PORT,Booklore/Secrets/DATABASE_URL,Booklore/Secrets/DB_USER,Booklore/Secrets/DB_PASSWORD";
    };
    dependsOn = [ "mariadb" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=booklore"
      "--network=booklore_default"
    ];
  };

  systemd.services."podman-booklore" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [ "podman-network-booklore_default.service" ];
    requires = [ "podman-network-booklore_default.service" ];
    partOf = [ "podman-compose-booklore-root.target" ];
    wantedBy = [ "podman-compose-booklore-root.target" ];
  };

  virtualisation.oci-containers.containers."mariadb" = {
    image = "lscr.io/linuxserver/mariadb:11.4.5";
    environment = {
      "MYSQL_DATABASE" = "/run/secrets/Booklore/Secrets/MYSQL_DATABASE";
      "MYSQL_PASSWORD" = "/run/secrets/Booklore/Secrets/DB_PASSWORD";
      "MYSQL_ROOT_PASSWORD" = "/run/secrets/Booklore/Secrets/MYSQL_ROOT_PASSWORD";
      "MYSQL_USER" = "/run/secrets/Booklore/Secrets/DB_USER";
      "PGID" = "/run/secrets/Booklore/Secrets/DB_GROUP_ID";
      "PUID" = "/run/secrets/Booklore/Secrets/DB_USER_ID";
      "TZ" = "/run/secrets/Booklore/Secrets/TZ";
    };
    volumes = [
      "/home/howard/Nix-servers/modules/docker_temp/booklore/mariadb/config:/config:rw"
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "Booklore/Secrets/DB_USER_ID,Booklore/Secrets/DB_GROUP_ID,Booklore/Secrets/TZ,Booklore/Secrets/DB_USER,Booklore/Secrets/DB_PASSWORD,Booklore/Secrets/MYSQL_ROOT_PASSWORD,Booklore/Secrets/MYSQL_DATABASE";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"mariadb-admin\", \"ping\", \"-h\", \"localhost\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=mariadb"
      "--network=booklore_default"
    ];
  };

  systemd.services."podman-mariadb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [ "podman-network-booklore_default.service" ];
    requires = [ "podman-network-booklore_default.service" ];
    partOf = [ "podman-compose-booklore-root.target" ];
    wantedBy = [ "podman-compose-booklore-root.target" ];
  };

  # Networks
  systemd.services."podman-network-booklore_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f booklore_default";
    };
    script = ''
      podman network inspect booklore_default || podman network create booklore_default
    '';
    partOf = [ "podman-compose-booklore-root.target" ];
    wantedBy = [ "podman-compose-booklore-root.target" ];
  };

  # Root service
  systemd.targets."podman-compose-booklore-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
