keys:
  - &Nixbox age1ehkj5ne2qtazxmhcu0633d4yesky4dppd9r744qzn5v9ly8s29xqw3hdje
creation_rules:
  - path_regex: host/secrets.yaml$
    key_groups:
    - age:
      - *Nixbox
  - path_regex: modules/common/secrets.yaml$
    key_groups:
    - age:
      - *Nixbox
