# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."booklore" = {
    image = "booklore/booklore:latest";
    environment = {
      "BOOKLORE_PORT" = "6060";
      "DATABASE_URL" = "jdbc:mariadb://mariadb:3306/booklore";
      "DATABASE_USERNAME" = "booklore";
      "MYSQL_PASSWORD_FILE" = config.sops.secrets."DB_PASSWORD".path;
      "GROUP_ID" = "0";
      "TZ" = "Etc/UTC";
      "USER_ID" = "0";
    };
    environmentFiles = [
      config.sops.secrets."DB_PASSWORD".path
    ];
    volumes = [
      "/home/howard/booklore/bookdrop:/bookdrop:rw"
      "/home/howard/booklore/books:/books:rw"
      "/home/howard/booklore/data:/app/data:rw"
    ];
    ports = [
      "6060:6060/tcp"
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "DB_PASSWORD";
    };
    dependsOn = [
      "mariadb"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=booklore"
      "--network=booklore_default"
    ];
  };
  systemd.services."podman-booklore" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-booklore_default.service"
    ];
    requires = [
      "podman-network-booklore_default.service"
    ];
    partOf = [
      "podman-compose-booklore-root.target"
    ];
    wantedBy = [
      "podman-compose-booklore-root.target"
    ];
  };
  virtualisation.oci-containers.containers."mariadb" = {
    image = "lscr.io/linuxserver/mariadb:11.4.5";
    environment = {
      "MYSQL_DATABASE" = "booklore";
      "MYSQL_USER" = "booklore";
      "MYSQL_PASSWORD_FILE" = config.sops.secrets."DB_PASSWORD".path;
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    environmentFiles = [
      config.sops.secrets."MYSQL_ROOT_PASSWORD".path
    ];
    volumes = [
      "/home/howard/booklore/mariadb/config:/config:rw"
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "MYSQL_ROOT_PASSWORD";
    };
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"mariadb-admin\", \"ping\", \"-h\", \"localhost\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=mariadb"
      "--network=booklore_default"
    ];
  };
  systemd.services."podman-mariadb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-booklore_default.service"
    ];
    requires = [
      "podman-network-booklore_default.service"
    ];
    partOf = [
      "podman-compose-booklore-root.target"
    ];
    wantedBy = [
      "podman-compose-booklore-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-booklore_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f booklore_default";
    };
    script = ''
      podman network inspect booklore_default || podman network create booklore_default
    '';
    partOf = [ "podman-compose-booklore-root.target" ];
    wantedBy = [ "podman-compose-booklore-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-booklore-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
