{
  pkgs,
  lib,
  config,
  ...
}:

let
  secretsMount = "/run/secrets";  # inside container
in
{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # DNS for Podman networks
  networking.firewall.interfaces =
    let matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in { "${matchAll}".allowedUDPPorts = [ 53 ]; };

  virtualisation.oci-containers.backend = "podman";

  # Booklore container
  virtualisation.oci-containers.containers."booklore" = {
    image = "booklore/booklore:latest";

    # Environment variables (Spring Boot will read DATABASE_PASSWORD from entrypoint)
    environment = {
      "BOOKLORE_PORT" = "6060";
      "DATABASE_URL" = "jdbc:mariadb://mariadb:3306/booklore";
      "DATABASE_USERNAME" = "booklore";
      "GROUP_ID" = "0";
      "TZ" = "Etc/UTC";
      "USER_ID" = "0";
    };

    # Mount SOPS secrets and data
    volumes = [
      "/home/howard/booklore/bookdrop:/bookdrop:rw"
      "/home/howard/booklore/books:/books:rw"
      "/home/howard/booklore/data:/app/data:rw"
      "/home/howard/secrets:${secretsMount}:ro"                 # SOPS secrets
      "/home/howard/booklore/entrypoint.sh:/app/entrypoint.sh:ro" # custom entrypoint
    ];

    ports = [ "6060:6060/tcp" ];

    labels = { "compose2nix.settings.sops.secrets" = "DB_PASSWORD,MYSQL_ROOT_PASSWORD"; };

    dependsOn = [ "mariadb" ];

    log-driver = "journald";

    extraOptions = [
      "--entrypoint=/app/entrypoint.sh"
      "--network=booklore_default"
      "--network-alias=booklore"
    ];
  };

  # MariaDB container
  virtualisation.oci-containers.containers."mariadb" = {
    image = "lscr.io/linuxserver/mariadb:11.4.5";

    environment = {
      "MYSQL_DATABASE" = "booklore";
      "MYSQL_USER" = "booklore";
      "MYSQL_PASSWORD_FILE" = "${secretsMount}/DB_PASSWORD";
      "MYSQL_ROOT_PASSWORD_FILE" = "${secretsMount}/MYSQL_ROOT_PASSWORD";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };

    volumes = [
      "/home/howard/booklore/mariadb/config:/config:rw"
      "/home/howard/secrets:${secretsMount}:ro"
    ];

    labels = { "compose2nix.settings.sops.secrets" = "MYSQL_ROOT_PASSWORD,DB_PASSWORD"; };

    log-driver = "journald";

    extraOptions = [
      "--health-cmd=[\"mariadb-admin\", \"ping\", \"-h\", \"localhost\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=mariadb"
      "--network=booklore_default"
    ];
  };

  # Systemd service for booklore
  systemd.services."podman-booklore" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [ "podman-network-booklore_default.service" ];
    requires = [ "podman-network-booklore_default.service" ];
    partOf = [ "podman-compose-booklore-root.target" ];
    wantedBy = [ "podman-compose-booklore-root.target" ];
  };

  # Systemd service for mariadb
  systemd.services."podman-mariadb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [ "podman-network-booklore_default.service" ];
    requires = [ "podman-network-booklore_default.service" ];
    partOf = [ "podman-compose-booklore-root.target" ];
    wantedBy = [ "podman-compose-booklore-root.target" ];
  };

  # Podman network
  systemd.services."podman-network-booklore_default" = {
    path = [ pkgs.podman ];
    serviceConfig = { Type = "oneshot"; RemainAfterExit = true; ExecStop = "podman network rm -f booklore_default"; };
    script = ''
      podman network inspect booklore_default || podman network create booklore_default
    '';
    partOf = [ "podman-compose-booklore-root.target" ];
    wantedBy = [ "podman-compose-booklore-root.target" ];
  };

  # Root target
  systemd.targets."podman-compose-booklore-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };
}
